version: '3'
services:
  backend:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    volumes:
      - ./backend:/srv/backend
    ports:
      - '1337:1337'
    depends_on:
      - db
    networks:
      - app

  db:
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
    networks:
      - app
  frontend:
    build:
      context: ./
      dockerfile: frontend.dev.Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/var/www/
      - ./frontend:/usr/src/app/
      - ./frontend/node_modules:/usr/src/app/node_modules
      - ./frontend/.next:/usr/src/app/.next
    depends_on:
      - backend
    networks:
      - app
  prediction_engine:
    build:
      context: ./
      dockerfile: prediction_engine.dev.Dockerfile
    restart: always
    ports:
      - "8888:8888"
    networks:
      - app
      - monitoring
  # backend:
  #   build:
  #     context: ./
  #     dockerfile: backend.dev.Dockerfile
  #   restart: always
  #   volumes:
  #     - ./backend/app:/srv/app
  #   ports:
  #     - '1337:1337'
  #   depends_on:
  #     - db
  #   networks:
  #     - app

  # db:
  #   image: mariadb
  #   volumes:
  #     - ./backend/data:/var/lib/mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: backend
  #     MYSQL_USER: strapi
  #     MYSQL_PASSWORD: strapi
  #   networks:
  #     - app

networks:
  app:
  monitoring:
